version: "3.8"
services:
  postgresql:
    image: postgres:16.2
    container_name: fommu_db
    restart: always
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./postgres/data:/var/lib/postgresql/data
      - ./postgres/dbscripts/001-init.sql:/docker-entrypoint-initdb.d/init.sql
